{
 "title": "MYAPP DASHBOARD",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "q", "query": "50,95,99,100" }
  ]
 },
 "panels": [
  {
   "title": "Latency APP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($q/100, sum by (le) (rate(sanic_request_latency_sec_bucket{}[2m]))) * 1000",
     "legendFormat": "$q"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(sanic_request_latency_sec_bucket{}[2m]))) * 1000",
     "legendFormat": "99"
    }
   ]
  },
  {
   "title": "Latency NGINX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($q/100, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) * 1000",
     "legendFormat": "$q"
    }
   ]
  },
  {
   "title": "RPS APP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint, method) (rate(sanic_request_count_total{}[2m]))",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "RPS NGINX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count[2m])"
    }
   ]
  },
  {
   "title": "Error rate APP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status, exported_endpoint, method) (rate(sanic_request_count_total{http_status!~\"2.*\"}[2m]))",
     "legendFormat": "{{method}} {{exported_endpoint}} {{http_status}}"
    }
   ]
  },
  {
   "title": "Error rate NGINX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_requests{status!~\"2.*\"}[2m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "APP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Latency distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sanic_request_latency_sec_bucket[15m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}